MATCH (person:Person {id: $personId})<-[:hasCreator]-(:Message)
    <-[:replyOf]-
    (comment:Comment)-[:hasCreator]->(commentAuthor:Person)
RETURN
    commentAuthor.id AS commentAuthorId,
    commentAuthor.firstName AS commentAuthorFirstName,
    commentAuthor.lastName AS commentAuthorLastName,
    comment.creationDate AS commentCreationDate,
    comment.id AS commentId,
    comment.content AS commentContent
ORDER BY
    commentCreationDate DESC,
    commentId ASC
LIMIT 20;
